apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: IBMPowerVSCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: openshift-cluster-api
spec:
  serviceInstanceID: ${IBMPOWERVS_SERVICE_INSTANCE_ID}
  network:
    regex: ${IBMPOWERVS_NETWORK_REGEX}
