apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-capi-operator-images
  namespace: openshift-cluster-api
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
data:
  images.json: >
    {
      "clusterCAPIOperator": "registry.ci.openshift.org/openshift:cluster-capi-operator"
    }
