apiVersion: v1
kind: Service
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/core: capi-operator
    control-plane: controller-manager
  name: capi-operator-controller-manager-metrics-service
  namespace: openshift-cluster-api
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    clusterctl.cluster.x-k8s.io/core: capi-operator
    control-plane: controller-manager
